# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OW/ASME Project Documentation
email: eric.wind@getopenwater.com
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for ASME's customizations on the OpenWater platform
domain: vindhaus.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://vindhaus.github.io/asmedocs  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /_site/      # place folder name if the site is served in a subfolder


# Build settings
remote-theme: just-the-docs
plugins:
  - jekyll-feed
color_scheme: owdefaultcolor
logo: "/assets/images/doclogo.png"

destination: ./docs

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   - docs/*
#   - !docs/.gitkeep

# Dark mode toggle // src: https://github.com/pmarsceill/just-the-docs/blob/31fce9c1b06da6f31d2043a3dc83e14df081b713/_config.yml
aux_links:
  '<button id="theme-toggle"></button>':
    - '#"onclick="modeSwitcher()"'
